# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='foo',
  serialized_pb='\n\x0emessages.proto\x12\x03\x66oo\" \n\x0e\x42\x61lanceRequest\x12\x0e\n\x06msisdn\x18\x01 \x02(\x05\"[\n\x07\x42\x61lance\x12\x0e\n\x06\x63redit\x18\x01 \x02(\x02\x12\x10\n\x08\x63urrency\x18\x02 \x02(\t\x12\x13\n\x0bvalid_until\x18\x03 \x02(\x03\x12\x0b\n\x03sms\x18\x04 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x02(\x05\"(\n\x06\x43redit\x12\x0e\n\x06\x61mount\x18\x01 \x02(\x02\x12\x0e\n\x06status\x18\x02 \x01(\t2:\n\nFooService\x12,\n\x07\x62\x61lance\x12\x13.foo.BalanceRequest\x1a\x0c.foo.BalanceB\x03\x90\x01\x01')




_BALANCEREQUEST = _descriptor.Descriptor(
  name='BalanceRequest',
  full_name='foo.BalanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msisdn', full_name='foo.BalanceRequest.msisdn', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=55,
)


_BALANCE = _descriptor.Descriptor(
  name='Balance',
  full_name='foo.Balance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='credit', full_name='foo.Balance.credit', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='foo.Balance.currency', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valid_until', full_name='foo.Balance.valid_until', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sms', full_name='foo.Balance.sms', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='foo.Balance.data', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=148,
)


_CREDIT = _descriptor.Descriptor(
  name='Credit',
  full_name='foo.Credit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='foo.Credit.amount', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='foo.Credit.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=150,
  serialized_end=190,
)

DESCRIPTOR.message_types_by_name['BalanceRequest'] = _BALANCEREQUEST
DESCRIPTOR.message_types_by_name['Balance'] = _BALANCE
DESCRIPTOR.message_types_by_name['Credit'] = _CREDIT

class BalanceRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BALANCEREQUEST

  # @@protoc_insertion_point(class_scope:foo.BalanceRequest)

class Balance(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BALANCE

  # @@protoc_insertion_point(class_scope:foo.Balance)

class Credit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREDIT

  # @@protoc_insertion_point(class_scope:foo.Credit)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_FOOSERVICE = _descriptor.ServiceDescriptor(
  name='FooService',
  full_name='foo.FooService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=192,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='balance',
    full_name='foo.FooService.balance',
    index=0,
    containing_service=None,
    input_type=_BALANCEREQUEST,
    output_type=_BALANCE,
    options=None,
  ),
])

class FooService(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _FOOSERVICE
class FooService_Stub(FooService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _FOOSERVICE

# @@protoc_insertion_point(module_scope)
